### ISSUE TITLE
i got error 

### ISSUE THREAD

**Issue by ssmadhu80** [janezkranjc/twitter-tap#3]
when i run this ccode i gor errorrs
om
[2015-04-22 22:59:27,392] DEBUG: "POST /oauth2/token HTTP/1.1" 200 152
[2015-04-22 22:59:27,398] WARNING: Access token: AAAAAAAAAAAAAAAAAAAAAIKCfQAAAAA
AeM560LlfLr2RWGsOMdXnIgVdSUY%3DwgsJZVG3RBJUgXglOI2jnCzTL1A6r6DaJ3od1LcW0T0zpoZgq
c
Traceback (most recent call last):
  File "tap.py", line 277, in <module>
    main()
  File "tap.py", line 145, in main
    queries.ensure_index([("query",pymongo.ASCENDING),("geocode",pymongo.ASCENDI
NG),("lang",pymongo.ASCENDING)],unique=True)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 1181, in ensu
re_index
    self.__create_index(keys, kwargs)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 1065, in __cr
eate_index
    with self._socket_for_writes() as sock_info:
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\pymongo\mongo_client.py", line 651, in _ge
t_socket
    server = self._get_topology().select_server(selector)
  File "C:\Python27\lib\site-packages\pymongo\topology.py", line 113, in select_
server
    server_selection_timeout))
  File "C:\Python27\lib\site-packages\pymongo\topology.py", line 93, in select_s
ervers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 10061] No co
nnection could be made because the target machine actively refused it

C:\twitter-tap-master\twitter_tap>

why?
how can i  resolve it

**Comment by janezkranjc** [comment]
do you have mongodb installed? this looks to me like a problem with connecting to your mongodb database

**Comment by ssmadhu80** [comment]
yes i have installed tested
with give command mongod and mongo exe file

**Comment by janezkranjc** [comment]
is mongod running while you are running tap?

**Comment by ssmadhu80** [comment]
hi
i got this error   File "C:\twitter-tap-master\twitter_tap\tap.py", line 167
    except TwythonError, err:
                       ^
SyntaxError: invalid syntax
while running twitter-tap

thanks
S.Madhu

**Comment by nothubnorspoke** [comment]
Same problem here. Any attempt to run tap, even with no arguments, results in line 167 twython error. This happens whether mongod is running or not.

**Comment by janezkranjc** [comment]
ok, I think this is python2 vs python3 error, I will fix this

**Comment by janezkranjc** [comment]
I fixed this, let me know if you encounter any further errors.
